server:
  port: 8089

elasticjob:
  server-list: 127.0.0.1:2181
  name-space: boot-job

#spring:
#  datasource:
#      url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&verifyServerCertificate=false&useSSL=false&requireSSL=false
#      driver-class-name: com.mysql.jdbc.Driver
#      username: root
#      password: root
#      type: com.zaxxer.hikari.HikariDataSource



# redis 连接配置
spring:
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    ssl: false
    pool:
        max-active: 10
        max-idle: 10
        max-wait: 600000
